### ISSUE TITLE
Breaks my pixel launcher

### ISSUE THREAD

**Issue by AbsurdumDaemonium** [symbuzzer/livebootmodule#12]
When I have this module enabled and only when I have this module enabled, pixel launcher breaks with these logs, 

`time: 1717657524506
msg: java.lang.SecurityException: Permission Denial: getRootTaskInfo() from pid=22180, uid=10568 requires android.permission.MANAGE_ACTIVITY_TASKS
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity}: java.lang.SecurityException: Permission Denial: getRootTaskInfo() from pid=22180, uid=10568 requires android.permission.MANAGE_ACTIVITY_TASKS
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3822)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3963)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2468)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.SecurityException: Permission Denial: getRootTaskInfo() from pid=22180, uid=10568 requires android.permission.MANAGE_ACTIVITY_TASKS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3045)
	at android.os.Parcel.readException(Parcel.java:3028)
	at android.os.Parcel.readException(Parcel.java:2970)
	at android.app.IActivityTaskManager$Stub$Proxy.getRootTaskInfo(IActivityTaskManager.java:3106)
	at com.android.quickstep.RecentsAnimationDeviceState.<init>(SourceFile:47)
	at com.android.quickstep.RecentsAnimationDeviceState.<init>(SourceFile:1)
	at com.android.quickstep.util.SplitWithKeyboardShortcutController.<init>(Unknown Source:13)
	at com.android.launcher3.uioverrides.QuickstepLauncher.setupViews(Unknown Source:68)
	at com.google.android.apps.nexuslauncher.NexusLauncherActivity.setupViews(Unknown Source:7)
	at com.android.launcher3.Launcher.onCreate(Unknown Source:160)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(Unknown Source:4)
	at com.google.android.apps.nexuslauncher.NexusLauncherActivity.onCreate(Unknown Source:0)
	at android.app.Activity.performCreate(Activity.java:8639)
	at android.app.Activity.performCreate(Activity.java:8617)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1462)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3804)
	... 12 more
`

**Comment by AbsurdumDaemonium** [comment]
> Can you try to remove this module and try liveboot app from Google Play and report again please?

yes, the same issue happens
